name: Potfolio-angular

services:

  portfolio-angular:
      container_name: portfolio-angular
      build: .
      ports:
        - "4200:4200"
      networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true